### ISSUE TITLE
Signature error

### ISSUE THREAD

**Issue by Hrnozz** [JKorf/FTX.Net#12]
2021.11.02 15:13:24:418 | Debug | FTX        | [1] Creating request for https://ftx.com/api/orders
2021.11.02 15:13:24:463 | Debug | FTX        | [1] Sending POST signed request to https://ftx.com/api/orders with request body {"externalReferralProgram":"jkorf-net","market":"GODS/USD","price":"3","side":"buy","size":"10","type":"limit"}
2021.11.02 15:13:24:494 | Debug | FTX        | Disposing exchange client
2021.11.02 15:13:25:005 | Debug | FTX        | [1] Error received: {"success":false,"error":"Not logged in"}

****
 Error received: {"success":false,"error":"Not logged in"}
****

i think I'm getting an error caused by hmac. How can i fix it?

**Comment by JKorf** [comment]
I've been running into this occasionally for periods, though for me it seems to be fine most of the time. Looking at the docs it's probably because the local computer time offset vs the server time. I'll work on a fix for this, based on the same solution the Binance library has.

The most robust option would probably be to make sure your local time is synced more often using some third party tool

**Comment by Hrnozz** [comment]
thanks for fixing the issue along with the latest version FTX.Net: v0.1.8.0
